### ISSUE TITLE
Consider using CommonJS code generation instead of esnext

### ISSUE THREAD

**Issue by AE-MS** [twop/ts-describe-action#1]
Because this module uses the 'esnext' code generation setting in tsconfig.json, it is difficult to consume from a NodeJS application since Node does not support ES6 modules in a straightforward way (it either requires some experimental flags or using babel to transpile the ES6 module into CommonJS, as far as I can tell).

It would be nice if this was a CommonJS module instead so it could be directly consumed by a NodeJS app.

I changed a local version of ts-describe-action from esnext to CommonJS to test and was then successfully able to use it in both a NodeJS app (yay!) and a web/webpack app.  As such, I don't know if there are any downsides to switching from esnext to CommonJS.

**Comment by twop** [comment]
Thanks for the feedback! Sure :)

**Comment by twop** [comment]
I released & published new version 2.1.1 
It has have both nodejs and esnext modules

commit details: https://github.com/twop/ts-describe-action/commit/4fa5b756f46c8be05e8b7a43b1b9ae30542c7017

**Comment by twop** [comment]
@AE-MS checkout new api in 2.2.0 version. Note it is fully backwards compatible

**Comment by AE-MS** [comment]
Great, thanks!
